alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists delivery_instructions text;

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  customer_email text,
  label text not null default 'Home',
  recipient_name text not null,
  phone text not null,
  address_line1 text not null,
  address_line2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists addresses_user_id_idx on public.addresses (user_id);
alter table public.addresses enable row level security;
