create table if not exists public.products (
  id bigint generated by default as identity primary key,
  barcode text, brand text,
  name text not null, category text not null, unit text not null,
  price numeric(10,2) not null, mrp numeric(10,2) not null,
  emoji text not null default '🛍️', image_url text, stock integer not null default 0,
  active boolean not null default true, created_at timestamptz not null default now()
);

alter table public.products add column if not exists barcode text;
alter table public.products add column if not exists brand text;
alter table public.products add column if not exists image_url text;
create unique index if not exists products_barcode_unique on public.products (barcode);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_email text not null, customer_name text not null,
  address text not null, payment_method text not null,
  amount numeric(10,2) not null, status text not null default 'Packing',
  created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null, product_name text not null,
  quantity integer not null check (quantity > 0), unit_price numeric(10,2) not null
);
create table if not exists public.payment_sessions (
  id uuid primary key, amount numeric(10,2) not null, phone text not null,
  status text not null default 'awaiting_merchant', expires_at bigint not null,
  created_at timestamptz not null default now()
);
create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null, desktop_key text not null, mobile_key text not null,
  active boolean not null default true, created_at timestamptz not null default now()
);
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payment_sessions enable row level security;
alter table public.banners enable row level security;
insert into storage.buckets (id, name, public) values ('banners', 'banners', false) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do update set public = true;

insert into public.products (name, category, unit, price, mrp, emoji, stock)
select * from (values
  ('Mango Banganapalli','Fresh','1 kg',119,149,'🥭',24),('Farm Fresh Bananas','Fresh','1 kg',55,65,'🍌',38),('Nandini Toned Milk','Dairy','1 L',58,60,'🥛',42),('Daily Fresh Bread','Dairy','400 g',42,50,'🍞',20),('Premium Potatoes','Fresh','1 kg',39,49,'🥔',31),('Tropicana Orange Juice','Drinks','1 L',110,125,'🧃',15),('Chocolate Cookies','Snacks','300 g',79,95,'🍪',25),('Classic Salted Popcorn','Snacks','90 g',45,55,'🍿',19),('Premium Sona Masoori Rice','Pantry','5 kg',349,425,'🍚',12),('Aloe Fresh Body Wash','Care','250 ml',165,199,'🧴',9),('Healthy Pet Dog Food','Pet','1.2 kg',299,349,'🐶',8),('Farm Fresh Eggs','Dairy','6 pcs',72,84,'🥚',27)
) as seed(name, category, unit, price, mrp, emoji, stock) where not exists (select 1 from public.products);
